// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"Gacha","status":true,"description":"Get the item at random","parameters":{"Help Message Text":"1回Required Amount 魔法石","Button Text":"轉蛋","Get Message Text":"GET Item Name","Show Item Description":"0","Effect":"119","Rank1 Effect":"122","Rank2 Effect":"123","Rank3 Effect":"124","Rank4 Effect":"125","Rank5 Effect":"126","ME":"Victory1","Required Item ID":"5","Required Amount":"5"}},
{"name":"GachaBook","status":true,"description":"Displays detailed statuses of \"gacha\" items.","parameters":{"Unknown Data":"??????","Price Text":"Price","Equip Text":"Equip","Type Text":"Type","Rank Text":"Rank","Simple Display":"1"}},
{"name":"EnemyBook","status":true,"description":"Displays detailed statuses of enemies.","parameters":{"Unknown Data":"??????"}},
{"name":"MrTS_PartyManager","status":true,"description":"Allows to check and change your party.","parameters":{"In Menu":"False","Command Name":"Party","Party Text":"隊伍","Members Text":"成員","Required Text":"必要隊員:","Draw TP":"False"}}
];
